# Command: sam local invoke -e event.json TestIntegration

AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  lambda template nodejs test

Resources:
  TestIntegration:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/index.handler
      Runtime: nodejs12.x
      Timeout: 50000
      MemorySize: 512
      Environment:
        Variables:
          NODE_ENV: development
